name: indigonotes

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:80
    secrets:
      - supa_key
      - supa_url
      - rsa_psw
      - rsa_priv_key
      - indigonotes_key
      - courier_key

secrets:
  supa_key:
    environment: service_role_key
  supa_url:
    environment: supa_url
  rsa_psw:
    environment: rsa_psw
  rsa_priv_key:
    file: myprivatekey.pem
  indigonotes_key:
    environment: indigonotes_api_key
  courier_key:
    environment: courier_auth_token